version: "3.7"

services:
    api:
        image: neberizer/babble 
        working_dir: /app
        environment:
            FLASK_APP: /app/app.py
            ENV_FILE_PATH: ./.env
        deploy:
            labels:
                traefik.http.routers.babble.rule: PathPrefix(`/api`)
                traefik.http.services.babble.loadbalancer.server.port: 5000
            replicas: 2
            placement:
                constraints:
                    - "node.role==worker"
            
    proxy:
        image: traefik:v2.1
        command: --api.insecure=true --providers.docker --providers.docker.swarmMode=true
        ports:
        - 80:80
        - 8080:8080
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            placement:
                constraints:
                    - "node.role==manager"

    mongo:
        image: mongo   
        deploy:
            placement:
                constraints:
                    - "node.role==worker"

    client:
        image: vtcs2304s19/blabber-client
        deploy:
            labels:
                traefik.http.routers.client.rule: PathPrefix(`/`)
                traefik.http.services.client.loadbalancer.server.port: 80
            replicas: 2
            placement:
                constraints:
                    - "node.role==worker"      

volumes:
    grafana-storage:
