version: "3.7"

services:
    api:
        build: ./
        image: neberizer/babble #image to import
        working_dir: /app #sets working directory
        volumes:
            - ./:/app
        environment:
            FLASK_ENV: development
            FLASK_APP: /app/app.py
        labels:
            traefik.http.routers.babble.rule: PathPrefix(`/api`) #.flask can be anything

    proxy:
        image: traefik:v2.1
        command: --api.insecure=true --providers.docker
        ports:
        - 80:80
        - 8080:8080
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock

    # tests:
    #     image: vtcs2304s19/blabber-api-tests
    #     environment:
    #         SERVICE_NAME: api
    #         API_PORT: "80"         

#Equivalent to below:
# docker container run \
# -p 5000:5000 \
# -v $(pwd):/app \
# -w /app \
# -e FLASK_ENV=development \
# python-app


#docker-compose commands
#up - start stuff
#down - stop stuff
#logs - view logs